const words = [
  // Masculine words with -o, -i, -u
  { word: "litro", gender: "masculine", rule: "-o" },
  { word: "quilo", gender: "masculine", rule: "-o" },
  { word: "centímetro", gender: "masculine", rule: "-o" },
  { word: "amigo", gender: "masculine", rule: "-o" },
  { word: "pó", gender: "masculine", rule: "-o" },
  { word: "nó", gender: "masculine", rule: "-o" },
  { word: "kiwi", gender: "masculine", rule: "-i" },
  { word: "álibi", gender: "masculine", rule: "-i" },
  { word: "peru", gender: "masculine", rule: "-u" },
  { word: "canguru", gender: "masculine", rule: "-u" },
  { word: "guru", gender: "masculine", rule: "-u" },
  // Exceptions: some words of Greek origin with -a
  { word: "problema", gender: "masculine", rule: "-a (Greek origin)" },
  { word: "esquema", gender: "masculine", rule: "-a (Greek origin)" },
  { word: "tema", gender: "masculine", rule: "-a (Greek origin)" },
  { word: "diploma", gender: "masculine", rule: "-a (Greek origin)" },
  { word: "sistema", gender: "masculine", rule: "-a (Greek origin)" },
  { word: "cinema", gender: "masculine", rule: "-a (Greek origin)" },
  { word: "programa", gender: "masculine", rule: "-a (Greek origin)" },
  { word: "grama", gender: "masculine", rule: "-a (Greek origin)" },
  { word: "planeta", gender: "masculine", rule: "-a (Greek origin)" },
  { word: "mapa", gender: "masculine", rule: "-a (Greek origin)" },
  // Masculine with -e, é
  { word: "restaurante", gender: "masculine", rule: "-e" },
  { word: "tomate", gender: "masculine", rule: "-e" },
  { word: "café", gender: "masculine", rule: "-é" },
  { word: "balé", gender: "masculine", rule: "-é" },
  // Masculine with -au, -éu, -eu, -oi
  { word: "bacalhau", gender: "masculine", rule: "-au" },
  { word: "cacau", gender: "masculine", rule: "-au" },
  { word: "europeu", gender: "masculine", rule: "-eu" },
  { word: "liceu", gender: "masculine", rule: "-eu" },
  { word: "chapéu", gender: "masculine", rule: "-éu" },
  { word: "boi", gender: "masculine", rule: "-oi" },
  // Masculine with -m (except -gem)
  { word: "guaxinim", gender: "masculine", rule: "-m" },
  { word: "pinguim", gender: "masculine", rule: "-m" },
  { word: "jardim", gender: "masculine", rule: "-m" },
  { word: "armazém", gender: "masculine", rule: "-m" },
  { word: "dom", gender: "masculine", rule: "-m" },
  { word: "álbum", gender: "masculine", rule: "-m" },
  // Masculine with -l
  { word: "túnel", gender: "masculine", rule: "-l" },
  { word: "anel", gender: "masculine", rule: "-l" },
  { word: "Brasil", gender: "masculine", rule: "-l" },
  // Masculine with -r
  { word: "humor", gender: "masculine", rule: "-r" },
  { word: "calor", gender: "masculine", rule: "-r" },
  { word: "pladur", gender: "masculine", rule: "-r" },
  // Feminine with -a
  { word: "cama", gender: "feminine", rule: "-a" },
  { word: "casa", gender: "feminine", rule: "-a" },
  { word: "aparência", gender: "feminine", rule: "-a" },
  // Feminine with -ã
  { word: "maçã", gender: "feminine", rule: "-ã" },
  { word: "lã", gender: "feminine", rule: "-ã" },
  { word: "irmã", gender: "feminine", rule: "-ã" },
  { word: "cidadã", gender: "feminine", rule: "-ã" },
  // Feminine with -ção, -são, -ssão, -zão
  { word: "marcação", gender: "feminine", rule: "-ção" },
  { word: "caução", gender: "feminine", rule: "-ção" },
  { word: "pensão", gender: "feminine", rule: "-são" },
  { word: "ilusão", gender: "feminine", rule: "-são" },
  { word: "renovação", gender: "feminine", rule: "-ção" },
  { word: "comissão", gender: "feminine", rule: "-ssão" },
  { word: "profissão", gender: "feminine", rule: "-ssão" },
  { word: "razão", gender: "feminine", rule: "-zão" },
  // Feminine with -gem
  { word: "imagem", gender: "feminine", rule: "-gem" },
  { word: "mensagem", gender: "feminine", rule: "-gem" },
  { word: "massagem", gender: "feminine", rule: "-gem" },
  { word: "viagem", gender: "feminine", rule: "-gem" },
  // Feminine with -dade, -tade, -ude
  { word: "cidade", gender: "feminine", rule: "-dade" },
  { word: "verdade", gender: "feminine", rule: "-dade" },
  { word: "idade", gender: "feminine", rule: "-dade" },
  { word: "vontade", gender: "feminine", rule: "-tade" },
  { word: "saúde", gender: "feminine", rule: "-ude" },
  // Feminine with -ice
  { word: "velhice", gender: "feminine", rule: "-ice" },
  { word: "idiotice", gender: "feminine", rule: "-ice" },
  { word: "chatice", gender: "feminine", rule: "-ice" },
  // Words that can be of both genders
  { word: "voz", gender: ["masculine", "feminine"], rule: "both" },
  { word: "luz", gender: ["masculine", "feminine"], rule: "both" },
  { word: "paz", gender: ["masculine", "feminine"], rule: "both" },
  { word: "nariz", gender: ["masculine", "feminine"], rule: "both" },
  { word: "rapaz", gender: ["masculine", "feminine"], rule: "both" },
  { word: "arroz", gender: ["masculine", "feminine"], rule: "both" },
  { word: "cão", gender: ["masculine", "feminine"], rule: "both" },
  { word: "leão", gender: ["masculine", "feminine"], rule: "both" },
];

